name: Push Event Workflow

on: push

jobs:
  unit-testing: 
    runs-on: ubuntu-latest 


    steps:
    -  name: Checkout code
       uses: actions/checkout@v2 



    -  name: Install Package
       run: pip install pytest
            pip install --upgrade pip
            pip install torch===1.3.1 torchvision===0.4.2 -f             
            pip install -r requirements.txt
            
    -  name: Run tests
       run: pytest Test.py

