name: Push Event Workflow

on: push

jobs:
  unit-testing: 
    runs-on: ubuntu-latest 


    steps:
    -  name: Checkout code
       uses: actions/checkout@v2 



    -  name: Install Package
       run: pip install pytest
            pip install --upgrade pip
            pip install -r requirements.txt


